"""
Stages 7 & 8 Smoke Test and Verification Harness
"""

import os
import pytest
import numpy as np
import polars as pl
from sklearn.ensemble import RandomForestClassifier

from src.explain.global_explainer import GlobalModelExplainer
from src.explain.local_explainer import LocalLoanExplainer
from src.explain.counterfactuals import CounterfactualEngine
from src.explain.uncertainty import EnsembleUncertaintyEstimator
from src.llm.guardrails import HallucinationGuardrail
from src.llm.audit_logger import AuditTrailLogger
from src.llm.schemas import ReviewerSummarySchema

@pytest.fixture
def dummy_data():
    rng = np.random.default_rng(42)
    n = 250
    df = pl.DataFrame({
        "loan_id": [f"L{i}" for i in range(n)],
        "interest_rate": rng.uniform(0.03, 0.09, n),
        "current_ltv": rng.uniform(0.5, 1.1, n),
        "dti": rng.uniform(20.0, 50.0, n),
        "credit_score": rng.integers(580, 850, n),
        "current_balance": rng.uniform(50000, 500000, n),
        "vintage": rng.choice([2018, 2019, 2020], n),
        "origination_month": rng.choice([1, 2, 3, 4, 5, 6], n),
        "default_flag": rng.choice([0, 1], p=[0.8, 0.2], size=n)
    })
    return df

@pytest.fixture
def mock_models(dummy_data):
    features = ["interest_rate", "current_ltv", "dti", "credit_score", "current_balance"]
    X = dummy_data.select(features).to_pandas()
    y = dummy_data["default_flag"].to_pandas()
    
    rf_def = RandomForestClassifier(n_estimators=5, max_depth=2, random_state=42).fit(X, y)
    rf_prep = RandomForestClassifier(n_estimators=5, max_depth=2, random_state=43).fit(X, y)
    
    models = {"default": rf_def, "prepay": rf_prep}
    
    # Uncertainty ensemble predictors
    ensemble = []
    for s in [10, 20, 30]:
        rf = RandomForestClassifier(n_estimators=5, max_depth=2, random_state=s).fit(X, y)
        def make_pred(model):
            def predict(input_df: pl.DataFrame) -> pl.DataFrame:
                pdf = input_df.select(features).to_pandas()
                probs = model.predict_proba(pdf)[:, 1]
                return input_df.with_columns(pl.Series("prob_default", probs))
            return predict
        ensemble.append(make_pred(rf))
        
    return models, ensemble, features

def test_explainability_engine(dummy_data, mock_models):
    """TEST 1: Explainability Memory & Constraint Bounds"""
    models, ensemble, features = mock_models
    
    # 1. Global Explainer (Cap background sampling to max 200)
    bg_data = dummy_data.head(200)
    assert bg_data.height <= 200
    
    global_exp = GlobalModelExplainer(models, bg_data)
    global_exp.compute_shap()
    
    # Verify both models have shap values computed
    assert "default" in global_exp.shap_values
    assert "prepay" in global_exp.shap_values
    
    # 2. Counterfactual Engine constraints
    predict_fn = ensemble[0]
    # Add initial prob_default to find a high risk loan
    df_scored = predict_fn(dummy_data)
    high_risk_loan = df_scored.filter(pl.col("prob_default") > 0.35).head(1)
    
    # If no high risk loan generated by chance, mock one
    if high_risk_loan.height == 0:
        high_risk_loan = dummy_data.head(1).with_columns(pl.lit(0.8).alias("prob_default"))
        
    cf_engine = CounterfactualEngine(predict_fn, target_col="prob_default", threshold=0.10)
    cf_res = cf_engine.generate_counterfactual_prescription(high_risk_loan)
    
    # Assert immutable features didn't change
    adjustments = cf_res["adjustments"]
    immutable_features = ["loan_id", "vintage", "origination_month"]
    for feat in immutable_features:
        assert feat not in adjustments
        
    # 3. Epistemic Uncertainty Bounds
    unc_engine = EnsembleUncertaintyEstimator(ensemble, target_col="prob_default")
    unc_df = unc_engine.estimate_uncertainty(dummy_data)
    
    confidence_min = unc_df["model_confidence"].min()
    confidence_max = unc_df["model_confidence"].max()
    assert confidence_min >= 0.0
    assert confidence_max <= 1.0


def test_llm_governance(tmp_path):
    """TEST 2: LLM Hallucination Guardrail & Audit Log"""
    db_path = str(tmp_path / "llm_audit_trail.db")
    audit_logger = AuditTrailLogger(db_path=db_path)
    guardrail = HallucinationGuardrail(prob_tolerance=0.03)
    
    # Action A: Valid Response
    ml_actual_a = {"prob_default": 0.18, "anomaly_data": {"anomaly_score": 10}}
    llm_output_a = ReviewerSummarySchema(
        summary="Default probability is 18.0%.",
        risk_assessment="LOW",
        key_drivers=[],
        recommended_action="Auto-Approve",
        reviewer_notes="Clean.",
        grounding_citations=[],
        confidence_score=0.9
    )
    is_valid_a, status_a, output_a = guardrail.validate_numerical_consistency(llm_output_a, ml_actual_a)
    assert is_valid_a is True
    assert status_a == "PASSED"
    
    audit_logger.log_interaction(
        loan_id="L_VALID", prompt_template="mock", retrieved_context="mock", model_name="gemini-mock",
        raw_response=llm_output_a.model_dump_json(), parsed_json=output_a.model_dump_json(),
        guardrail_status=status_a, latency_seconds=1.0, human_reviewer_feedback="ACCEPTED"
    )
    
    # Action B: Hallucinated Response
    ml_actual_b = {"prob_default": 0.18, "anomaly_data": {"anomaly_score": 10}}
    llm_output_b = ReviewerSummarySchema(
        summary="Default probability is 45.0%.",
        risk_assessment="HIGH",
        key_drivers=[],
        recommended_action="Reject/Repurchase",
        reviewer_notes="High risk.",
        grounding_citations=[],
        confidence_score=0.9
    )
    is_valid_b, status_b, output_b = guardrail.validate_numerical_consistency(llm_output_b, ml_actual_b)
    assert is_valid_b is False
    assert status_b == "REJECTED_HALLUCINATION"
    
    audit_logger.log_interaction(
        loan_id="L_HALLUC", prompt_template="mock", retrieved_context="mock", model_name="gemini-mock",
        raw_response=llm_output_b.model_dump_json(), parsed_json=output_b.model_dump_json(),
        guardrail_status=status_b, latency_seconds=1.2, human_reviewer_feedback="REJECTED"
    )
    
    # Assert DB row count
    audit_df = audit_logger.export_audit_summary()
    assert audit_df.height == 2
