"""
Scenario Narrative Builder — scenario_narrator.py

Auto-generates an executive narrative report based on Monte Carlo bounds,
segment vulnerabilities, and tornado sensitivity outputs.
"""

from typing import Dict, List, Tuple
from src.utils.logger import get_logger

logger = get_logger(__name__)


class ScenarioNarrativeBuilder:
    """
    Translates quantitative stochastic outcomes into a plain-English 
    executive markdown report.
    """

    def __init__(self):
        pass

    def generate_report(
        self,
        mc_summaries: Dict[str, Dict[str, Dict[str, float]]],
        vulnerable_segments: List[Dict],
        sensitivities: Dict[str, Tuple[float, float]],
        output_path: str = "reports/SCENARIO_STRESS_REPORT.md"
    ):
        """
        Builds the Markdown report.

        Args:
            mc_summaries: { scenario_name: { metric: { mean, p_lower, p50, p_upper } } }
            vulnerable_segments: List of top vulnerable segments.
            sensitivities: Tornado sensitivity outputs.
        """
        logger.info("Generating executive scenario narrative report...")
        
        md_lines = [
            "# INTAIN-SIGHT: Executive Scenario & Stress Simulation Report",
            "",
            "> **CONFIDENTIAL**: Auto-generated by Verification Agent Simulation Engine",
            "",
            "## 1. Portfolio Value at Risk (VaR) & Macro Scenarios",
            "This section outlines the deterministic and stochastic portfolio impacts under core scenarios.",
            ""
        ]

        # 1. Macro Summary Table
        md_lines.extend([
            "| Scenario | Median Default Rate (P50) | Worst-Case Default Rate (P95) | Median CPR (P50) | Loss Severity (P50) |",
            "| :--- | :--- | :--- | :--- | :--- |"
        ])
        
        for sc_name, summary in mc_summaries.items():
            d_p50 = summary.get("default_rate", {}).get("p50", 0.0) * 100
            d_p95 = summary.get("default_rate", {}).get("p_upper", 0.0) * 100
            c_p50 = summary.get("cpr", {}).get("p50", 0.0) * 100
            l_p50 = summary.get("loss_severity", {}).get("p50", 0.0) * 100
            
            md_lines.append(
                f"| **{sc_name}** | {d_p50:.2f}% | {d_p95:.2f}% | {c_p50:.2f}% | {l_p50:.2f}% |"
            )
        
        md_lines.append("")

        # 2. Key Findings
        base_d = mc_summaries.get("Base", {}).get("default_rate", {}).get("p50", 0.0)
        adv_d = mc_summaries.get("Adverse-Credit", {}).get("default_rate", {}).get("p_upper", 0.0)
        risk_multiple = (adv_d / max(base_d, 0.0001))
        
        md_lines.extend([
            "### Key Findings",
            f"- Under severe economic stress (Adverse-Credit P95), the portfolio default rate expands by **{risk_multiple:.1f}x** compared to the Base scenario median.",
            ""
        ])

        # 3. Vulnerable Segments
        md_lines.extend([
            "## 2. Segment Vulnerability Concentration",
            "The following portfolio sub-segments exhibit the highest relative risk expansion under the Adverse-Credit shock:",
            ""
        ])
        
        for i, seg in enumerate(vulnerable_segments):
            base_r = seg['base_default_rate'] * 100
            adv_r = seg['adverse_default_rate'] * 100
            delta_pct = seg['relative_risk_delta'] * 100
            md_lines.append(
                f"{i+1}. **{seg['dimension']} = {seg['segment_value']}**: "
                f"Default rate shifts from {base_r:.2f}% to {adv_r:.2f}% "
                f"(**+{delta_pct:.1f}% relative risk delta**). Vol: {seg['loan_count']} loans."
            )
            
        md_lines.append("")

        # 4. Tornado Drivers
        md_lines.extend([
            "## 3. Macroeconomic Sensitivity (Tornado Analysis)",
            "Marginal impacts of isolated macroeconomic shocks on portfolio default propensity:",
            ""
        ])
        
        sorted_shocks = sorted(
            sensitivities.items(),
            key=lambda item: max(abs(item[1][0]), abs(item[1][1])),
            reverse=True
        )
        
        if sorted_shocks:
            dominant = sorted_shocks[0][0]
            md_lines.append(f"**Dominant Driver:** {dominant} exhibits the highest marginal impact on portfolio performance.")
            md_lines.append("")
            for k, (down, up) in sorted_shocks:
                md_lines.append(f"- **{k}**: Down Shock = {down*100:+.2f} pts | Up Shock = {up*100:+.2f} pts")
        else:
            md_lines.append("_No sensitivity data generated._")

        with open(output_path, "w") as f:
            f.write("\n".join(md_lines))
        
        logger.info(f"Narrative report successfully written to {output_path}")
